### ISSUE TITLE
Anchor childs missing

### ISSUE THREAD

**Issue by budoland-ab** [aune-io/magento2-product-grid-category-filter#1]
If category is an anchor Category and has no children itself no products are shown.

**Comment by renatocason** [comment]
Hi @budoland-ab ,

I just created a new version 1.1.0 with support for anchor categories.
They are disabled by default as with complex catalogues the grid might become messy, but it can be turned on via configuration. Instructions are in the readme.
Let me know if you get a chance to test it and if it works correctly for you!

Thanks,
Renato

**Comment by budoland-ab** [comment]
Works perfect now. Thank you.
