### ISSUE TITLE
PHP8 Compatibility

### ISSUE THREAD

**Issue by vseager** [aune-io/magento2-product-grid-category-filter#12]
Can't install with composer with PHP8:

```
[InvalidArgumentException]                                                                                                                       
  Package aune-io/magento2-product-grid-category-filter has requirements incompatible with your PHP version, PHP extensions and Composer version:  
    - aune-io/magento2-product-grid-category-filter 1.3.3 requires php ~7.1.0|~7.2.0|~7.3.0|~7.4.0 which does not match your installed version 8.  
  1.11.      
```

**Comment by renatocason** [comment]
Hi @vseager ,

I released version 1.3.4 with PHP 8 compatibility on the composer file:
https://github.com/aune-io/magento2-product-grid-category-filter/releases/tag/1.3.4

If you could test it out and let me know if it worked correctly on PHP 8.0/8.1 code-wise, that would be much appreciated.

**Comment by agelospanagiotakis** [comment]
also 8.2 compatibility ?

**Comment by renatocason** [comment]
Hi @agelospanagiotakis ,

You are welcome to open a PR and test support!

Thanks,
Renato
