### ISSUE TITLE
no categories gets a error.

### ISSUE THREAD

**Issue by bymem** [aune-io/magento2-product-grid-category-filter#2]
If you have no categories in your shop, the module results in a error in the product list.

**Comment by renatocason** [comment]
Hi @bymem ,

Thanks for reporting the issue, it's fixed on version 1.1.1!

Regards,
Renato

**Comment by bymem** [comment]
Thanks, But i have now installed it on a already existing shop, and now i can't the categories at all.
Both the filter list can't see any categories, have even tried creating a new categori but nothing shows up.

<img width="524" alt="screen shot 2018-10-29 at 13 15 14" src="https://user-images.githubusercontent.com/1265623/47649202-d160a680-db7c-11e8-842d-0b51818036f9.png">

And all products do not have a category label on them.

<img width="187" alt="screen shot 2018-10-29 at 13 15 19" src="https://user-images.githubusercontent.com/1265623/47649271-066cf900-db7d-11e8-93d8-4778bdeb707d.png">

Don't know if that is anything to do with the new update?

**Comment by renatocason** [comment]
Accidentally pushed a line of test code - can you try now with version 1.1.2?

Thanks,
Renato

**Comment by bymem** [comment]
Yup, that did the trick, seems to be working now.

**Comment by renatocason** [comment]
A `composer update` should do, depending on the version constraint you have in the composer.json file - if you followed the README instructions you should be fine.

**Comment by bymem** [comment]
commented just seconds before you ;-) It's working now.

**Comment by renatocason** [comment]
Amazing, sorry for the inconvenient and thanks for using the extension! :)
