### ISSUE TITLE
Can't sort ascending

### ISSUE THREAD

**Issue by ciancastillo** [aune-io/magento2-product-grid-category-filter#7]
When sorting to ascending, nothing happens

**Comment by renatocason** [comment]
Hi @ciancastillo ,

Sorting by category is not supported.
There are mainly two reasons for this:
* Each product could be assigned to more than one category, how would sorting work in this case?
* For performance and code complexity reasons, the list of categories is fetched from the database after the products list is loaded. The products list is loaded after pagination filters are applied, meaning that sorting would be inconsistent in case not all products fit in one page (which I guess is most of the times)

Despite that, if it's important for you, feel free to fork the repo and implement the functionality for yourself.  PRs are welcome as well if done according to Magento 2 best practices.

Regards,
Renato
